version: '3.8'

services:
  apache:
    image: php:8.0-apache
    container_name: apache-php
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mysql:latest
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 39451418
      MYSQL_DATABASE: docknet
      MYSQL_USER: user
      MYSQL_PASSWORD: 14183945
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 39451418
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  db_data: